apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: getshorty-appset
  namespace: cf-test
spec:
  generators:
    - git:
        repoURL: https://github.com/maryia-devops-room/secure-manifests.git
        revision: main
        directories:
          - path: '*'
  template:
    metadata:
      name: getshorty-{{path.basename}}  # app name will be like getshorty-prod
      annotations:
        codefresh.io/product: getshorty
      namespace: cf-test
    spec:
      project: restricted-test
      source:
        repoURL: https://github.com/maryia-devops-room/secure-manifests.git
        targetRevision: main
        path: '{{path}}'                # path from generator (prod, staging, etc.)
      destination:
        name: in-cluster
        namespace: cf-test   # deploy to namespace matching folder name
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
          allowEmpty: false
        syncOptions:
          - PrunePropagationPolicy=foreground
          - Replace=false
          - PruneLast=false
          - Validate=true
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=false
          - ServerSideApply=true
          - RespectIgnoreDifferences=false
